In [11]:
import os
import requests
import dotenv
import pandas as pd
import datetime

In [24]:
dotenv.load_dotenv('.env.prod')
import dotenv

api_key = dotenv.get_key('.env.prod', 'ALPHAVANTAGE_API_KEY')
symbol = 'AAPL'
url = f"https://www.alphavantage.co/query?function=HISTORICAL_OPTIONS&symbol={symbol}&require_greeks=true&apikey={api_key}"
response = requests.get(url)
data = response.json()
print(data)

{'endpoint': 'Historical Options', 'message': 'success', 'data': [{'contractID': 'AAPL251128C00110000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '110.00', 'type': 'call', 'last': '166.22', 'mark': '166.10', 'bid': '164.85', 'bid_size': '20', 'ask': '167.35', 'ask_size': '33', 'volume': '6', 'open_interest': '8', 'date': '2025-11-24', 'implied_volatility': '3.53187', 'delta': '0.99624', 'gamma': '0.00011', 'theta': '-0.15433', 'vega': '0.00323', 'rho': '0.01192'}, {'contractID': 'AAPL251128P00110000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '110.00', 'type': 'put', 'last': '0.01', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '1000', 'volume': '1', 'open_interest': '0', 'date': '2025-11-24', 'implied_volatility': '2.77091', 'delta': '-0.00046', 'gamma': '0.00002', 'theta': '-0.01628', 'vega': '0.00047', 'rho': '-0.00001'}, {'contractID': 'AAPL251128C00120000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '120.00', 'type': 'call', 'last': '150.80', 'mark': '156.12', 'bid': '154.90', 'bid_size': '20', 'ask': '157.35', 'ask_size': '30', 'volume': '0', 'open_interest': '6', 'date': '2025-11-24', 'implied_volatility': '3.25870', 'delta': '0.99551', 'gamma': '0.00014', 'theta': '-0.16728', 'vega': '0.00380', 'rho': '0.01299'}, {'contractID': 'AAPL251128P00120000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '120.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '1000', 'volume': '0', 'open_interest': '8', 'date': '2025-11-24', 'implied_volatility': '2.51726', 'delta': '-0.00050', 'gamma': '0.00002', 'theta': '-0.01601', 'vega': '0.00051', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00125000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '125.00', 'type': 'call', 'last': '145.77', 'mark': '151.12', 'bid': '149.90', 'bid_size': '20', 'ask': '152.35', 'ask_size': '30', 'volume': '0', 'open_interest': '2', 'date': '2025-11-24', 'implied_volatility': '3.10261', 'delta': '0.99536', 'gamma': '0.00015', 'theta': '-0.16468', 'vega': '0.00391', 'rho': '0.01354'}, {'contractID': 'AAPL251128P00125000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '125.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '1000', 'volume': '0', 'open_interest': '0', 'date': '2025-11-24', 'implied_volatility': '2.40019', 'delta': '-0.00052', 'gamma': '0.00003', 'theta': '-0.01600', 'vega': '0.00053', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00130000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '130.00', 'type': 'call', 'last': '141.01', 'mark': '146.12', 'bid': '144.90', 'bid_size': '20', 'ask': '147.35', 'ask_size': '30', 'volume': '0', 'open_interest': '5', 'date': '2025-11-24', 'implied_volatility': '2.96603', 'delta': '0.99507', 'gamma': '0.00017', 'theta': '-0.16669', 'vega': '0.00413', 'rho': '0.01408'}, {'contractID': 'AAPL251128P00130000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '130.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '1000', 'volume': '0', 'open_interest': '12', 'date': '2025-11-24', 'implied_volatility': '2.28312', 'delta': '-0.00054', 'gamma': '0.00003', 'theta': '-0.01565', 'vega': '0.00055', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00135000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '135.00', 'type': 'call', 'last': '140.97', 'mark': '141.12', 'bid': '139.90', 'bid_size': '20', 'ask': '142.35', 'ask_size': '30', 'volume': '1', 'open_interest': '2', 'date': '2025-11-24', 'implied_volatility': '2.80993', 'delta': '0.99504', 'gamma': '0.00018', 'theta': '-0.15983', 'vega': '0.00415', 'rho': '0.01462'}, {'contractID': 'AAPL251128P00135000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '135.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '750', 'volume': '0', 'open_interest': '0', 'date': '2025-11-24', 'implied_volatility': '2.16604', 'delta': '-0.00054', 'gamma': '0.00003', 'theta': '-0.01496', 'vega': '0.00055', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00140000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '140.00', 'type': 'call', 'last': '130.70', 'mark': '136.12', 'bid': '134.90', 'bid_size': '20', 'ask': '137.35', 'ask_size': '30', 'volume': '0', 'open_interest': '8', 'date': '2025-11-24', 'implied_volatility': '2.67335', 'delta': '0.99485', 'gamma': '0.00019', 'theta': '-0.15794', 'vega': '0.00429', 'rho': '0.01517'}, {'contractID': 'AAPL251128P00140000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '140.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '750', 'volume': '0', 'open_interest': '0', 'date': '2025-11-24', 'implied_volatility': '2.06849', 'delta': '-0.00059', 'gamma': '0.00003', 'theta': '-0.01546', 'vega': '0.00060', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00145000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '145.00', 'type': 'call', 'last': '131.03', 'mark': '131.12', 'bid': '129.90', 'bid_size': '20', 'ask': '132.35', 'ask_size': '30', 'volume': '1', 'open_interest': '2', 'date': '2025-11-24', 'implied_volatility': '2.55628', 'delta': '0.99445', 'gamma': '0.00021', 'theta': '-0.16164', 'vega': '0.00458', 'rho': '0.01570'}, {'contractID': 'AAPL251128P00145000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '145.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '750', 'volume': '0', 'open_interest': '3', 'date': '2025-11-24', 'implied_volatility': '1.97093', 'delta': '-0.00063', 'gamma': '0.00004', 'theta': '-0.01571', 'vega': '0.00064', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00150000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '150.00', 'type': 'call', 'last': '126.10', 'mark': '126.12', 'bid': '124.90', 'bid_size': '20', 'ask': '127.35', 'ask_size': '30', 'volume': '2', 'open_interest': '1', 'date': '2025-11-24', 'implied_volatility': '2.41970', 'delta': '0.99437', 'gamma': '0.00023', 'theta': '-0.15619', 'vega': '0.00464', 'rho': '0.01625'}, {'contractID': 'AAPL251128P00150000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '150.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '750', 'volume': '0', 'open_interest': '39', 'date': '2025-11-24', 'implied_volatility': '1.87337', 'delta': '-0.00067', 'gamma': '0.00004', 'theta': '-0.01570', 'vega': '0.00067', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00155000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '155.00', 'type': 'call', 'last': '121.16', 'mark': '121.15', 'bid': '119.90', 'bid_size': '20', 'ask': '122.40', 'ask_size': '30', 'volume': '2', 'open_interest': '3', 'date': '2025-11-24', 'implied_volatility': '2.36116', 'delta': '0.99302', 'gamma': '0.00028', 'theta': '-0.18192', 'vega': '0.00561', 'rho': '0.01675'}, {'contractID': 'AAPL251128P00155000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '155.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '42', 'volume': '0', 'open_interest': '12', 'date': '2025-11-24', 'implied_volatility': '1.77581', 'delta': '-0.00069', 'gamma': '0.00005', 'theta': '-0.01539', 'vega': '0.00069', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00160000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '160.00', 'type': 'call', 'last': '109.91', 'mark': '116.15', 'bid': '114.90', 'bid_size': '20', 'ask': '117.40', 'ask_size': '30', 'volume': '0', 'open_interest': '10', 'date': '2025-11-24', 'implied_volatility': '2.22458', 'delta': '0.99302', 'gamma': '0.00030', 'theta': '-0.17292', 'vega': '0.00561', 'rho': '0.01730'}, {'contractID': 'AAPL251128P00160000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '160.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '44', 'volume': '0', 'open_interest': '6', 'date': '2025-11-24', 'implied_volatility': '1.67825', 'delta': '-0.00071', 'gamma': '0.00005', 'theta': '-0.01480', 'vega': '0.00071', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00165000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '165.00', 'type': 'call', 'last': '0.00', 'mark': '111.15', 'bid': '109.90', 'bid_size': '20', 'ask': '112.40', 'ask_size': '30', 'volume': '0', 'open_interest': '0', 'date': '2025-11-24', 'implied_volatility': '2.10751', 'delta': '0.99271', 'gamma': '0.00033', 'theta': '-0.17095', 'vega': '0.00583', 'rho': '0.01784'}, {'contractID': 'AAPL251128P00165000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '165.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '48', 'volume': '0', 'open_interest': '122', 'date': '2025-11-24', 'implied_volatility': '1.60021', 'delta': '-0.00080', 'gamma': '0.00006', 'theta': '-0.01584', 'vega': '0.00079', 'rho': '-0.00003'}, {'contractID': 'AAPL251128C00170000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '170.00', 'type': 'call', 'last': '102.86', 'mark': '106.15', 'bid': '104.90', 'bid_size': '20', 'ask': '107.40', 'ask_size': '30', 'volume': '0', 'open_interest': '3', 'date': '2025-11-24', 'implied_volatility': '1.99044', 'delta': '0.99246', 'gamma': '0.00036', 'theta': '-0.16733', 'vega': '0.00601', 'rho': '0.01838'}, {'contractID': 'AAPL251128P00170000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '170.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '16', 'volume': '0', 'open_interest': '132', 'date': '2025-11-24', 'implied_volatility': '1.50265', 'delta': '-0.00079', 'gamma': '0.00006', 'theta': '-0.01466', 'vega': '0.00078', 'rho': '-0.00002'}, {'contractID': 'AAPL251128C00175000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '175.00', 'type': 'call', 'last': '96.85', 'mark': '101.15', 'bid': '99.90', 'bid_size': '20', 'ask': '102.40', 'ask_size': '30', 'volume': '0', 'open_interest': '1', 'date': '2025-11-24', 'implied_volatility': '1.89288', 'delta': '0.99178', 'gamma': '0.00041', 'theta': '-0.17174', 'vega': '0.00648', 'rho': '0.01890'}, {'contractID': 'AAPL251128P00175000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '175.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '60', 'volume': '0', 'open_interest': '340', 'date': '2025-11-24', 'implied_volatility': '1.42460', 'delta': '-0.00087', 'gamma': '0.00007', 'theta': '-0.01525', 'vega': '0.00086', 'rho': '-0.00003'}, {'contractID': 'AAPL251128C00180000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '180.00', 'type': 'call', 'last': '87.46', 'mark': '96.18', 'bid': '94.95', 'bid_size': '20', 'ask': '97.40', 'ask_size': '30', 'volume': '0', 'open_interest': '2', 'date': '2025-11-24', 'implied_volatility': '1.81483', 'delta': '0.99050', 'gamma': '0.00049', 'theta': '-0.18580', 'vega': '0.00736', 'rho': '0.01941'}, {'contractID': 'AAPL251128P00180000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '180.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '26', 'volume': '0', 'open_interest': '54', 'date': '2025-11-24', 'implied_volatility': '1.34655', 'delta': '-0.00096', 'gamma': '0.00008', 'theta': '-0.01567', 'vega': '0.00093', 'rho': '-0.00003'}, {'contractID': 'AAPL251128C00185000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '185.00', 'type': 'call', 'last': '85.67', 'mark': '91.22', 'bid': '90.10', 'bid_size': '9', 'ask': '92.35', 'ask_size': '31', 'volume': '0', 'open_interest': '5', 'date': '2025-11-24', 'implied_volatility': '1.75630', 'delta': '0.98835', 'gamma': '0.00060', 'theta': '-0.21232', 'vega': '0.00879', 'rho': '0.01989'}, {'contractID': 'AAPL251128P00185000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '185.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '27', 'volume': '0', 'open_interest': '64', 'date': '2025-11-24', 'implied_volatility': '1.26851', 'delta': '-0.00104', 'gamma': '0.00009', 'theta': '-0.01589', 'vega': '0.00100', 'rho': '-0.00003'}, {'contractID': 'AAPL251128C00190000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '190.00', 'type': 'call', 'last': '80.15', 'mark': '86.18', 'bid': '84.95', 'bid_size': '20', 'ask': '87.40', 'ask_size': '30', 'volume': '0', 'open_interest': '8', 'date': '2025-11-24', 'implied_volatility': '1.60021', 'delta': '0.98965', 'gamma': '0.00059', 'theta': '-0.17853', 'vega': '0.00793', 'rho': '0.02048'}, {'contractID': 'AAPL251128P00190000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '190.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '24', 'volume': '0', 'open_interest': '304', 'date': '2025-11-24', 'implied_volatility': '1.19046', 'delta': '-0.00111', 'gamma': '0.00011', 'theta': '-0.01588', 'vega': '0.00107', 'rho': '-0.00003'}, {'contractID': 'AAPL251128C00195000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '195.00', 'type': 'call', 'last': '75.43', 'mark': '81.18', 'bid': '79.95', 'bid_size': '20', 'ask': '82.40', 'ask_size': '30', 'volume': '0', 'open_interest': '5', 'date': '2025-11-24', 'implied_volatility': '1.50265', 'delta': '0.98893', 'gamma': '0.00067', 'theta': '-0.17836', 'vega': '0.00841', 'rho': '0.02101'}, {'contractID': 'AAPL251128P00195000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '195.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '24', 'volume': '0', 'open_interest': '120', 'date': '2025-11-24', 'implied_volatility': '1.11241', 'delta': '-0.00117', 'gamma': '0.00012', 'theta': '-0.01562', 'vega': '0.00113', 'rho': '-0.00004'}, {'contractID': 'AAPL251128C00200000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '200.00', 'type': 'call', 'last': '68.77', 'mark': '76.18', 'bid': '74.95', 'bid_size': '22', 'ask': '77.40', 'ask_size': '30', 'volume': '0', 'open_interest': '101', 'date': '2025-11-24', 'implied_volatility': '1.40509', 'delta': '0.98822', 'gamma': '0.00076', 'theta': '-0.17685', 'vega': '0.00888', 'rho': '0.02153'}, {'contractID': 'AAPL251128P00200000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '200.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '44', 'volume': '0', 'open_interest': '720', 'date': '2025-11-24', 'implied_volatility': '1.03437', 'delta': '-0.00122', 'gamma': '0.00014', 'theta': '-0.01509', 'vega': '0.00117', 'rho': '-0.00004'}, {'contractID': 'AAPL251128C00205000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '205.00', 'type': 'call', 'last': '69.20', 'mark': '71.18', 'bid': '69.95', 'bid_size': '20', 'ask': '72.40', 'ask_size': '30', 'volume': '1', 'open_interest': '13', 'date': '2025-11-24', 'implied_volatility': '1.30753', 'delta': '0.98752', 'gamma': '0.00086', 'theta': '-0.17392', 'vega': '0.00933', 'rho': '0.02206'}, {'contractID': 'AAPL251128P00205000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '205.00', 'type': 'put', 'last': '0.00', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '52', 'volume': '0', 'open_interest': '349', 'date': '2025-11-24', 'implied_volatility': '0.95632', 'delta': '-0.00126', 'gamma': '0.00015', 'theta': '-0.01428', 'vega': '0.00120', 'rho': '-0.00004'}, {'contractID': 'AAPL251128C00210000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '210.00', 'type': 'call', 'last': '65.41', 'mark': '66.15', 'bid': '65.35', 'bid_size': '11', 'ask': '66.95', 'ask_size': '11', 'volume': '3', 'open_interest': '105', 'date': '2025-11-24', 'implied_volatility': '1.19046', 'delta': '0.98798', 'gamma': '0.00091', 'theta': '-0.15643', 'vega': '0.00904', 'rho': '0.02262'}, {'contractID': 'AAPL251128P00210000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '210.00', 'type': 'put', 'last': '0.01', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '89', 'volume': '1', 'open_interest': '393', 'date': '2025-11-24', 'implied_volatility': '0.87827', 'delta': '-0.00126', 'gamma': '0.00016', 'theta': '-0.01320', 'vega': '0.00121', 'rho': '-0.00004'}, {'contractID': 'AAPL251128C00215000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '215.00', 'type': 'call', 'last': '61.07', 'mark': '61.17', 'bid': '59.95', 'bid_size': '20', 'ask': '62.40', 'ask_size': '30', 'volume': '4', 'open_interest': '64', 'date': '2025-11-24', 'implied_volatility': '1.11241', 'delta': '0.98624', 'gamma': '0.00109', 'theta': '-0.16361', 'vega': '0.01015', 'rho': '0.02312'}, {'contractID': 'AAPL251128P00215000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '215.00', 'type': 'put', 'last': '0.01', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '104', 'volume': '1', 'open_interest': '267', 'date': '2025-11-24', 'implied_volatility': '0.81974', 'delta': '-0.00156', 'gamma': '0.00021', 'theta': '-0.01495', 'vega': '0.00146', 'rho': '-0.00005'}, {'contractID': 'AAPL251128C00220000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '220.00', 'type': 'call', 'last': '56.45', 'mark': '56.17', 'bid': '54.95', 'bid_size': '20', 'ask': '57.40', 'ask_size': '61', 'volume': '12', 'open_interest': '187', 'date': '2025-11-24', 'implied_volatility': '1.01485', 'delta': '0.98570', 'gamma': '0.00124', 'theta': '-0.15612', 'vega': '0.01050', 'rho': '0.02365'}, {'contractID': 'AAPL251128P00220000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '220.00', 'type': 'put', 'last': '0.01', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.01', 'ask_size': '35', 'volume': '170', 'open_interest': '3750', 'date': '2025-11-24', 'implied_volatility': '0.74169', 'delta': '-0.00153', 'gamma': '0.00023', 'theta': '-0.01327', 'vega': '0.00144', 'rho': '-0.00005'}, {'contractID': 'AAPL251128C00222500', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '222.50', 'type': 'call', 'last': '50.35', 'mark': '53.70', 'bid': '52.45', 'bid_size': '20', 'ask': '54.95', 'ask_size': '30', 'volume': '0', 'open_interest': '11', 'date': '2025-11-24', 'implied_volatility': '0.99534', 'delta': '0.98305', 'gamma': '0.00146', 'theta': '-0.17423', 'vega': '0.01214', 'rho': '0.02384'}, {'contractID': 'AAPL251128P00222500', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '222.50', 'type': 'put', 'last': '0.01', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.02', 'ask_size': '111', 'volume': '37', 'open_interest': '125', 'date': '2025-11-24', 'implied_volatility': '0.70267', 'delta': '-0.00150', 'gamma': '0.00024', 'theta': '-0.01233', 'vega': '0.00141', 'rho': '-0.00005'}, {'contractID': 'AAPL251128C00225000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '225.00', 'type': 'call', 'last': '51.13', 'mark': '50.98', 'bid': '50.50', 'bid_size': '11', 'ask': '51.45', 'ask_size': '51', 'volume': '1', 'open_interest': '264', 'date': '2025-11-24', 'implied_volatility': '0.01976', 'delta': '1.00000', 'gamma': '0.00000', 'theta': '-0.02391', 'vega': '0.00000', 'rho': '0.02465'}, {'contractID': 'AAPL251128P00225000', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '225.00', 'type': 'put', 'last': '0.01', 'mark': '0.01', 'bid': '0.00', 'bid_size': '0', 'ask': '0.02', 'ask_size': '122', 'volume': '149', 'open_interest': '1700', 'date': '2025-11-24', 'implied_volatility': '0.68315', 'delta': '-0.00190', 'gamma': '0.00031', 'theta': '-0.01487', 'vega': '0.00175', 'rho': '-0.00006'}, {'contractID': 'AAPL251128C00227500', 'symbol': 'AAPL', 'expiration': '2025-11-28', 'strike': '

In [25]:
data = data.get("data", [])
data_df = pd.DataFrame(data)
data_df

,contractID,symbol,expiration,strike,type,last,mark,bid,bid_size,ask,ask_size,volume,open_interest,date,implied_volatility,delta,gamma,theta,vega,rho
0,AAPL251128C00110000,AAPL,2025-11-28,110.00,call,166.22,166.10,164.85,20,167.35,33,6,8,2025-11-24,3.53187,0.99624,0.00011,-0.15433,0.00323,0.01192
1,AAPL251128P00110000,AAPL,2025-11-28,110.00,put,0.01,0.01,0.00,0,0.01,1000,1,0,2025-11-24,2.77091,-0.00046,0.00002,-0.01628,0.00047,-0.00001
2,AAPL251128C00120000,AAPL,2025-11-28,120.00,call,150.80,156.12,154.90,20,157.35,30,0,6,2025-11-24,3.25870,0.99551,0.00014,-0.16728,0.00380,0.01299
3,AAPL251128P00120000,AAPL,2025-11-28,120.00,put,0.00,0.01,0.00,0,0.01,1000,0,8,2025-11-24,2.51726,-0.00050,0.00002,-0.01601,0.00051,-0.00002
4,AAPL251128C00125000,AAPL,2025-11-28,125.00,call,145.77,151.12,149.90,20,152.35,30,0,2,2025-11-24,3.10261,0.99536,0.00015,-0.16468,0.00391,0.01354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2669,AAPL280121P00510000,AAPL,2028-01-21,510.00,put,0.00,234.25,232.00,2,236.50,2,0,0,2025-11-24,0.54657,-0.60221,0.00174,-0.01157,1.56400,-8.66677
2670,AAPL280121C00520000,AAPL,2028-01-21,520.00,call,3.93,3.90,3.75,16,4.05,2,102,522,2025-11-24,0.25390,0.09893,0.00169,-0.01383,0.70594,0.49954
2671,AAPL280121P00520000,AAPL,2028-01-21,520.00,put,0.00,244.25,242.00,2,246.50,2,0,0,2025-11-24,0.54657,-0.61151,0.00173,-0.01010,1.55377,-8.89263
2672,AAPL280121C00530000,AAPL,2028-01-21,530.00,call,3.65,3.55,3.40,13,3.70,27,19,933,2025-11-24,0.25390,0.09033,0.00158,-0.01289,0.66016,0.45742
2673,AAPL280121P00530000,AAPL,2028-01-21,530.00,put,0.00,254.25,252.00,2,256.50,2,0,0,2025-11-24,0.56608,-0.60573,0.00168,-0.01126,1.56023,-9.09513

In [28]:
data_df.to_csv('data.csv')

In [32]:
target_delta_range = (0.5, 1.0)
target_dtm_range = (15, 30)
today = datetime.datetime.now()
time_range_low = today - datetime.timedelta(days=target_dtm_range[0])
time_range_high = today + datetime.timedelta(days=target_dtm_range[1])
data_df['expiration'] = pd.to_datetime(data_df['expiration'])
data_df['delta'] = data_df['delta'].astype(float)
mask = (
    (data_df['delta'].abs() >= target_delta_range[0])
    & (data_df['delta'].abs() <= target_delta_range[1])

)
filtered_data = data_df[mask] 
filtered_data

,contractID,symbol,expiration,strike,type,last,mark,bid,bid_size,ask,ask_size,volume,open_interest,date,implied_volatility,delta,gamma,theta,vega,rho
0,AAPL251128C00110000,AAPL,2025-11-28,110.00,call,166.22,166.10,164.85,20,167.35,33,6,8,2025-11-24,3.53187,0.99624,0.00011,-0.15433,0.00323,0.01192
2,AAPL251128C00120000,AAPL,2025-11-28,120.00,call,150.80,156.12,154.90,20,157.35,30,0,6,2025-11-24,3.25870,0.99551,0.00014,-0.16728,0.00380,0.01299
4,AAPL251128C00125000,AAPL,2025-11-28,125.00,call,145.77,151.12,149.90,20,152.35,30,0,2,2025-11-24,3.10261,0.99536,0.00015,-0.16468,0.00391,0.01354
6,AAPL251128C00130000,AAPL,2025-11-28,130.00,call,141.01,146.12,144.90,20,147.35,30,0,5,2025-11-24,2.96603,0.99507,0.00017,-0.16669,0.00413,0.01408
8,AAPL251128C00135000,AAPL,2025-11-28,135.00,call,140.97,141.12,139.90,20,142.35,30,1,2,2025-11-24,2.80993,0.99504,0.00018,-0.15983,0.00415,0.01462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,AAPL280121P00490000,AAPL,2028-01-21,490.00,put,0.00,214.25,212.00,2,216.50,2,0,0,2025-11-24,0.50755,-0.61214,0.00186,-0.00936,1.55305,-8.25613
2667,AAPL280121P00500000,AAPL,2028-01-21,500.00,put,0.00,224.25,222.00,2,226.50,2,0,0,2025-11-24,0.52706,-0.60730,0.00180,-0.01046,1.55851,-8.46174
2669,AAPL280121P00510000,AAPL,2028-01-21,510.00,put,0.00,234.25,232.00,2,236.50,2,0,0,2025-11-24,0.54657,-0.60221,0.00174,-0.01157,1.56400,-8.66677
2671,AAPL280121P00520000,AAPL,2028-01-21,520.00,put,0.00,244.25,242.00,2,246.50,2,0,0,2025-11-24,0.54657,-0.61151,0.00173,-0.01010,1.55377,-8.89263
2673,AAPL280121P00530000,AAPL,2028-01-21,530.00,put,0.00,254.25,252.00,2,256.50,2,0,0,2025-11-24,0.56608,-0.60573,0.00168,-0.01126,1.56023,-9.09513

In [30]:
filtered_data.to_csv('filtered_data.csv')